import sys
import os
import time

def read_data(input_file):
    
    file = []
    try:
        lines = input_file.readlines()
        for line in lines:
            temp = list(map(int, line.split(', ')))
            file.append(temp)
    except:
        return file

    return file

def isCorrect(test, label):

    if len(test) == len(label):
        Is_True = 1
        for i in range(len(test)):
            if test[i] != label[i]:
                Is_True = 0
                break;
        return Is_True
    else:
        return 0

def grading(hw):
    score = 0
    test_files = ["output_10.txt", "output_20.txt", "output_30.txt", "output_40.txt", "output_50.txt", 
                    "output_60.txt", "output_70.txt", "output_80.txt", "output_90.txt", "output_100.txt"]
    label_files = ["sm_output_10.txt", "sm_output_20.txt", "sm_output_30.txt", "sm_output_40.txt", "sm_output_50.txt", 
                    "sm_output_60.txt", "sm_output_70.txt", "sm_output_80.txt", "sm_output_90.txt", "sm_output_100.txt"]

    for i in range(len(test_files)):

        #read output generated by assigment
        test_file = open(test_files[i], 'r')
        test = read_data(test_file)
        test_file.close()
        #read sample output
        label_file = open(label_files[i], 'r')
        label = read_data(label_file)
        label_file.close()
        #grading
        score += isCorrect(test, label)

    print(hw[:-3] + ':     ', 100 * score / len(test_files))

def readAssignments():

    file = open('Assignments.txt', 'r')
    assignments = []
    try:
        lines = file.readlines()
        for line in lines:
            assignments.append(line[:-1] + '.py')
    except:
        print("Error in reading data")
    file.close()
    return assignments

def generateResult(hw):
    hw = '../Assignments/' + hw 
    os.system("python " + hw + " sm_10.txt > output_10.txt")
    os.system("python " + hw + " sm_20.txt > output_20.txt")
    os.system("python " + hw + " sm_30.txt > output_30.txt")
    os.system("python " + hw + " sm_40.txt > output_40.txt")
    os.system("python " + hw + " sm_50.txt > output_50.txt")
    os.system("python " + hw + " sm_60.txt > output_60.txt")
    os.system("python " + hw + " sm_70.txt > output_70.txt")
    os.system("python " + hw + " sm_80.txt > output_80.txt")
    os.system("python " + hw + " sm_90.txt > output_90.txt")
    os.system("python " + hw + " sm_100.txt > output_100.txt")

def main():
    assignments = readAssignments()
    assignmentNumber = len(assignments)
    for hw in assignments:
        start = time.time()
        generateResult(hw)
        grading(hw)
        end = time.time()
        print("Time:", end - start )

if __name__=="__main__":
    main()